export const ADD_USER_SUCCESS="ADD_USER_SUCCESS"
export const ADD_USER_FAIL='ADD_USER_FAIL'
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"
export const GET_CURRENT_SUCCESS="GET_CURRENT_SUCCESS"
export const GET_CURRENT_FAIL="GET_CURRENT_FAIL"
 
export const LOGOUT="LOGOUT"
export const REGISTER_FAIL="REGISTER_FAIL"
export const  GET_ALLUSER_SUCCESS=" GET_ALLUSER_SUCCESS"
export const GET_ALLUSER_FAIL="GET_ALLUSER_FAIL"
export const REGISTER_SUCCESS="REGISTER_SUCCESS"